export interface LineRange {
  startLine: number // 0-indexed, inclusive
  endLine: number // 0-indexed, exclusive
}

function normalize(s: string): string {
  return s.replace(/\s+/g, ' ').trim().toLowerCase()
}

/**
 * Map a rendered-HTML text selection back to a line range in the raw HTML
 * source. The reviewed page is rendered inside a sandboxed iframe, so the only
 * signal we get from a selection is its visible text. We locate that text
 * within the source (tags stripped from the comparison is unnecessary — the
 * visible text usually appears verbatim between tags) and return the source
 * lines it spans.
 *
 * Best-effort by design: if the selection can't be located (e.g. it's text
 * generated by script, or split awkwardly across tags), returns null and the
 * caller declines to open a comment rather than anchoring to the wrong place.
 */
export function findLineRange(source: string, selectedText: string): LineRange | null {
  const selNorm = normalize(selectedText)
  if (!selNorm) return null

  const lines = source.split('\n')
  const normLines = lines.map(normalize)

  // Distinctive leading / trailing chunks of the selection. Short enough to
  // survive whitespace normalization differences, long enough to be specific.
  const head = selNorm.slice(0, 24)
  const tail = selNorm.slice(-24)

  let start = -1
  let end = -1
  for (let i = 0; i < normLines.length; i++) {
    const nl = normLines[i]
    if (!nl) continue
    if (start === -1 && nl.includes(head)) start = i
    if (nl.includes(tail)) end = i
  }

  // Fallback: try to find any single line that contains the whole selection
  // (common for short, single-line selections).
  if (start === -1) {
    for (let i = 0; i < normLines.length; i++) {
      if (normLines[i] && normLines[i].includes(selNorm.slice(0, 40))) {
        start = i
        end = i
        break
      }
    }
  }

  if (start === -1) return null
  if (end < start) end = start
  return { startLine: start, endLine: end + 1 }
}
